### ISSUE TITLE
Removal of some mods

### ISSUE THREAD

**Issue by Adaptivity** [ZeroLevels/modlist#739]
I've finally decided to remove most Calclavia's mods (sorry but I'm tired). I've already removed Resonant Induction, Modular Force Field System but the problem arised when I've faced with Universal Electricity. The problem is that this is a dependency if I'll remove it I need to remove every mod which are depend on it... or not? I don't know what to do now this is why I asking.

Current mod status:
ICBM for 1.6.2 and lower -> check, downloads archived. Depends on UE.
ICBM for 1.6.4 -> check, uploaded on curse. Latest version depends only on Forge.
ICBM for 1.7.10 -> check.
Resonant Engine both 1.6.4 and 1.7.10 -> check.
Voltz Engine -> check.
Modular Force Field System -> removed.
Resonant Induction -> removed.
Hawk's Machinery -> check, downloads archived. Depends on UE.
Mad Science -> check, downloads on curse. Depends on UE.
Metal Mechanics -> removed, downloads are dead.
Minechem 1.6.4 -> check, downloads on curse. Depends on UE.
Modular Powersuits 1.5.2 and lower -> check, downloads are up. Depends on UE.

Solution №1: Remove all mods that are depends on UE and all other references to UE (Simple solution).

Solution №2: Remove mods with dead links, remove UE (and refs in descs) but leave UE as unclickable dependency in alive mods dependencies. So, if you click on UE in Minechem deps for example nothing happens. (users have to search for UE themselves)

Solution №3: We should try to contact with someone from former UE Team and yell at them to reupload UE on curse if it still exist somewhere (it should exist in modpacks btw) and maybe some other UE mods. I suggest to ping DarkGuardsman if you @GrygrFlzr want to try this solution.

Personally I suggest at least try solution №3. If fail, I'll prefer solution №2.

**Comment by GrygrFlzr** [comment]
After doing a little digging, seems like Universal Electricity has been absorbed into Calclavia's upcoming [Electrodynamics](http://calclavia.com/electrodynamics/) mod ([repo](https://github.com/calclavia/Electrodynamics)), which depends on the [NOVA wrapper](http://novaapi.net/). The page for Electrodynamics seems misleading since there seems to be no available release yet, but it certainly doesn't look like it'd be compatible with the old mods that depend on it.
There is a [legacy download page](http://calclavia.com/electrodynamics/maven/) for the old mods, however it is ***infested*** with popups and ads. Frankly, I'd like to avoid linking to such a mess. The page includes MFFS, Resonant Induction, and UE itself.
A direct link to the last available build for each of those may be our best option.
- [Universal Electricity Core 3.1.0.99](https://calclavia.s3.amazonaws.com/maven/universalelectricity/Universal-Electricity/3.1.0.99/Universal-Electricity-3.1.0.99-core.jar)
- [MFFS 3.6.3.91](https://calclavia.s3.amazonaws.com/maven/mffs/mffs/3.6.3.91/mffs-3.6.3.91-core.jar)
- Resonant Induction 0.3.1.259
 - [Core](https://calclavia.s3.amazonaws.com/maven/resonantinduction/core/0.3.1.259/core-0.3.1.259-core.jar)
 - [Electrical](https://calclavia.s3.amazonaws.com/maven/resonantinduction/core/0.3.1.259/core-0.3.1.259-electrical.jar)
 - [Mechanical](https://calclavia.s3.amazonaws.com/maven/resonantinduction/core/0.3.1.259/core-0.3.1.259-mechanical.jar)

That leaves Metal Mechanics, which does not have a working download link but still has a [github repository](https://github.com/Lycanite/MetalMech) up. I think it's worth keeping it, and perhaps I can persuade @Lycanite to provide a new direct download (or ask for permission to host one).

**Comment by Lycanite** [comment]
You can get a direct download link from Copy.com which is the main host I use, I also upload to Curse.
To get the direct link, follow through adfly to the copy.com download page then right click on the download button at the top right and copy the link address. Here's the latest so far:
https://copy.com/N3NjhwKQCKe7v27r/LycanitesMobsComplete%201.11.0.6%20%5B1.7.10%5D.jar

**Comment by Adaptivity** [comment]
We're talking about Metal Mechanics hehe.

**Comment by Lycanite** [comment]
Ooooh lol! XD Feel free to rehost that one then! XD

**Comment by Adaptivity** [comment]
Can we have a copy of this then?
@GrygrFlzr Ok, then we have files. Now I'm pinging @DarkGuardsman. 
Dear @DarkGuardsman, is there are any chance that you can set up curse pages for listed mods? Only for archive purposes of course.

**Comment by DarkGuardsman** [comment]
Which mods do you need pages for?

**Comment by Adaptivity** [comment]
1) Universal Electricity. We need latest versions for 1.6.4, 1.6.2, 1.5.2, 1.5.1, 1.4.7, 1.4.5 (If it possible to find them)
1.6.4 and 1.6.2 needed for Minechem and Mad Science (1.6.2 can be removed from the list since it's minor)
1.5.2, 1.5.1, 1.4.7 needed for Modular Powersuits, Metal Mechanics
1.4.5 needed for Hawk's Machinery
2) Modular Force Field System 1.6.4 and 1.7.10
3) Resonant Induction 1.6.4 and 1.7.10
4) And if possible any versions of Atomic Science (It got removed from list but can be restored if we have actual page)

UE have highest priority. I also can help you with finding latest versions of mods for different MC versions using link @GrygrFlzr provided.

**Comment by Adaptivity** [comment]
Ok, for the links.
1) Universal Electricity:
[4.0.0.9](http://calclavia.com/electrodynamics/maven/?prefix=maven/dev/calclavia/universalelectricity/universal-electricity/4.0.0.9/) latest available version for MC 1.7.10
[3.1.0.99](http://calclavia.com/electrodynamics/maven/?prefix=maven/universalelectricity/Universal-Electricity/3.1.0.99/) latest available version for MC 1.6.4.
However, I can't find downloads for lower MC versions.
2) Modular Force Field System
[4.1.1.74](http://calclavia.com/electrodynamics/maven/?prefix=maven/dev/calclavia/mffs/mffs/4.1.1.74/) for MC 1.7.10
[3.6.3.91](http://calclavia.com/electrodynamics/maven/?prefix=maven/mffs/mffs/3.6.3.91/) for MC 1.6.4
3) Resonant Induction
[0.3.5.301](http://calclavia.com/electrodynamics/maven/?prefix=maven/dev/calclavia/resonantinduction/resonant-induction/0.3.5.301/) seems to be latest 1.7.10 version
[0.3.1.259](http://calclavia.com/electrodynamics/maven/?prefix=maven/resonantinduction/core/0.3.1.259/) latest 1.6.4. Also, [archaic module](http://calclavia.com/electrodynamics/maven/?prefix=maven/dev/calclavia/resonantinduction/resonant-induction/0.3.5.301/)
4) Atomic Science
[1.2.0.83](http://calclavia.com/electrodynamics/maven/?prefix=maven/atomicscience/atomic-science/1.2.0.83/) for MC 1.6.4

**Comment by DarkGuardsman** [comment]
Most likely i can do UE on curse. Madscience is already listed on curse. As for RI, AS, and MFFS i will need to talk to @Calclavia. The rest you need to hunt down the authors of those mods. As i don't haven permission to rehost thier files.

**Comment by Adaptivity** [comment]
Yeah, UE would be great. Talk to @Calclavia when you have time.

**Comment by calclavia** [comment]
@GrygrFlzr Can you confirm those versions of my mod are working? If so I'll put those links onto the main page of the download site so people don't have to look through each folder in the Maven repository.

**Comment by Adaptivity** [comment]
@GrygrFlzr meh, that's too hard. We'll never find all those mods for different MC versions. The maven link you are provided contains even not latest versions (we even don't know which versions are stable) for MC 1.6.4 but we still need versions for other MC versions. If nobody have an archive with all those versions, there are nothing we can do then. I'm for removing everything. Entirely.

**Comment by DarkGuardsman** [comment]
I got permission to rehost the files from calcalvia, and have downloaded most of his maven. I'll upload a few files on curse and the rest on sourceforge. I'll give it a go to test the versions as well but can't promise any kind of stability.

**Comment by Adaptivity** [comment]
Ok, thanks for your input. That's a great news.
